steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        REGION="us-east1"
        REPO_ARTIFACT="test-bolivar-agendamiento"
        IMAGE_REPO="test-bolivar-agendamiento"
        SERVICE_NAME="test-bolivar-agendamiento"
        IMAGE_NAME="${REGION}-docker.pkg.dev/$PROJECT_ID/${REPO_ARTIFACT}/${IMAGE_REPO}:latest"

        echo "REGION=$REGION" >> $BUILD_ENV
        echo "REPO_ARTIFACT=$REPO_ARTIFACT" >> $BUILD_ENV
        echo "IMAGE_REPO=$IMAGE_REPO" >> $BUILD_ENV
        echo "SERVICE_NAME=$SERVICE_NAME" >> $BUILD_ENV
        echo "IMAGE_NAME=$IMAGE_NAME" >> $BUILD_ENV

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        source $BUILD_ENV
        if gcloud artifacts repositories describe "$REPO_ARTIFACT" --location="$REGION" >/dev/null 2>&1; then
          echo "Repositorio ya existe, no se hace nada."
        else
          echo "Creando repositorio..."
          gcloud artifacts repositories create "$REPO_ARTIFACT" \
            --location "$REGION" \
            --description "Repo de backend para la IA de agendamiento de citas" \
            --repository-format="DOCKER"
        fi

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        source $BUILD_ENV
        docker build -t "$IMAGE_NAME" --network=cloudbuild .
        docker push "$IMAGE_NAME"

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        source $BUILD_ENV
        gcloud run deploy "$SERVICE_NAME" \
          --image "$IMAGE_NAME" \
          --region "$REGION" \
          --platform managed \
          --allow-unauthenticated

options:
  logging: CLOUD_LOGGING_ONLY